# Production Docker Compose Stack für Angular Frontend
# Image: physio-prod-frontend
# Ports: 4202/4202
# Usage: docker compose -f compose.prod.yml up -d

services:
  physio-prod-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: physio-prod
    image: physio-prod-frontend:latest
    restart: unless-stopped
    environment:
      API_URL: http://localhost:8082
    ports:
      - "4202:80"
      - "4202:443"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 64M
    networks:
      - physio-prod-network

networks:
  physio-prod-network:
    name: physio-prod-network
    driver: bridge
    external: true